version: '3.8'

services:
  victoria-metrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoria-metrics
    ports:
      - "8428:8428"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - victoria-metrics-data:/victoria-metrics-data
    command:
      - '--promscrape.config=/etc/prometheus/prometheus.yml'
      - '--storageDataPath=/victoria-metrics-data'
      - '--retentionPeriod=100d'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_DATASOURCES_NAME=VictoriaMetrics
      - GF_DATASOURCES_TYPE=prometheus
      - GF_DATASOURCES_URL=http://victoria-metrics:8428
      - GF_DATASOURCES_ACCESS=proxy
      - GF_DATASOURCES_IS_DEFAULT=true
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - victoria-metrics
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  victoria-metrics-data:
  grafana-data: 
